// <auto-generated />
namespace ZTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SettingsModelchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SettingsModelchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201705300800583_Settings Model changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
